name             'versionone'
maintainer       'VersionOne, Inc.'
maintainer_email 'joe.koberg@versionone.com'
license          'MIT/BSD'
description      'Installs/Configures VersionOne'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.1'
depends			 'iis'
depends			 'windows'
depends			 'chocolatey'
